table Sheet1
	lineageTag: f065e1fa-8de4-4cb2-8f2b-4f7a0b5a4300

	column a
		dataType: string
		lineageTag: 1c9ee22d-5145-4ff7-a3f6-aa5b2caa5747
		summarizeBy: none
		sourceColumn: a
		sortByColumn: order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column b
		dataType: int64
		formatString: 0
		lineageTag: 00a64f76-08f8-4beb-ab32-6c8c7f8972c0
		summarizeBy: sum
		sourceColumn: b

		annotation SummarizationSetBy = Automatic

	column order
		dataType: string
		lineageTag: 6d27c5a5-bbd5-4312-9e96-7a945d2c6b86
		summarizeBy: none
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	partition Sheet1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\gavin.ransom\OneDrive - OneWorkplace\Documents\Power Bi\git-demo\data.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"a", type text}, {"b", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

