table Table
	lineageTag: 135563f2-f8ab-4ae1-8212-533a2199eeac

	column month
		dataType: string
		lineageTag: af9a9bf3-a1be-4aa2-9da1-251aa3f90cdf
		summarizeBy: none
		sourceColumn: month
		sortByColumn: order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column value
		dataType: int64
		formatString: 0
		lineageTag: 702d6c1f-3734-4bd5-afad-1371c003963d
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column order
		dataType: int64
		formatString: 0
		lineageTag: a24999ba-bb07-479b-928e-a91c2aa73723
		summarizeBy: sum
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Nc5LCoAgFIXhvdxxg+zdWqSBlQVRKr2g3XfPLSc/8WF6tKbFOEooSzmKukTTZHtAhghsZsd3xckFTBDIOcV/4gG0nFJguVz8pfphBdSc+rvjmgEFpxE4bIjQCvjhBCgMS0Wcv7FBpn5bRzvEdxSP7V4=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [month = _t, value = _t, order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"month", type text}, {"value", Int64.Type}, {"order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

